package com.mh.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name = "T_WEB_BANK_HUIKUAN")
public class TWebBankHuikuan {

//	private Double youhui;// 公司入款，赠送优惠
//	
//	public Double getYouhui() {
//		return youhui;
//	}
//	
//	public void setYouhui(Double youhui) {
//		this.youhui = youhui;
//	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)//自增长
	@Column(name = "ID",nullable = false)
	private Integer id;

	@Column(name = "HK_ORDER")
	private String hkOrder;

	@Column(name = "USER_NAME")
	private String userName;

	@Column(name = "HK_TYPE")
	private String hkType;
	
	@Column(name = "HK_ONLINE_PAY_NO")
	private String hkOnlinePayNo;
	
	@Column(name = "HK_MONEY")
	private Double hkMoney;
	
	@Column(name = "HK_COMPANY_BANK")
	private String hkCompanyBank;

	@Column(name = "HK_USER_BANK")
	private String hkUserBank;

	@Column(name = "HK_USER_NAME")
	private String hkUserName;
	
	@Column(name = "HK_IP")
	private String hkIp;
	
	@Column(name = "HK_TIME")
	private Date hkTime;
	
	@Column(name = "HK_STATUS")
	private Integer hkStatus;
	
	@Column(name = "HK_MODEL")
	private Integer hkModel;
	
	@Column(name = "MODIFY_TIME")
	private Date modifyTime;
	
	@Column(name = "REMARK")
	private String remark;
	
	@Column(name = "HK_CHECK_TIME")
	private Date hkCheckTime;
	
	@Column(name = "HK_CHECK_SYS_USER_NAME")
	private String hkCheckSysUserName;
	
	@Column(name = "CREATE_TIME")
	private Date createTime;
	
	@Column(name = "HK_CHECK_STATUS")
	private Integer hkCheckStatus;
	
	@Column(name = "GMT_4_TIME")
	private Date gmt4Time;
	
	@Column(name = "TOTAL_TIMES")
	private Integer totalTimes;
	
	@Column(name = "DAY_TIMES")
	private Integer dayTimes;
	
	@Column(name = "PAY_DAMA")
	private Integer payDama;
	
	@Column(name = "PAY_DEFAULT")
	private Integer payDefault;
	
	@Column(name = "HK_YOUHUI")
	private Integer hkYouhui;

	@Column(name = "PAY_NO")
	private String payNo;
	
	
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.id
	 * 
	 * @param id
	 *            the value for t_web_bank_huikuan.id
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_order
	 * 
	 * @return the value of t_web_bank_huikuan.hk_order
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getHkOrder() {
		return hkOrder;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_order
	 * 
	 * @param hkOrder
	 *            the value for t_web_bank_huikuan.hk_order
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkOrder(String hkOrder) {
		this.hkOrder = hkOrder;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.user_name
	 * 
	 * @return the value of t_web_bank_huikuan.user_name
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.user_name
	 * 
	 * @param userName
	 *            the value for t_web_bank_huikuan.user_name
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_type
	 * 
	 * @return the value of t_web_bank_huikuan.hk_type
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getHkType() {
		return hkType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_type
	 * 
	 * @param hkType
	 *            the value for t_web_bank_huikuan.hk_type
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkType(String hkType) {
		this.hkType = hkType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_online_pay_no
	 * 
	 * @return the value of t_web_bank_huikuan.hk_online_pay_no
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getHkOnlinePayNo() {
		return hkOnlinePayNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_online_pay_no
	 * 
	 * @param hkOnlinePayNo
	 *            the value for t_web_bank_huikuan.hk_online_pay_no
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkOnlinePayNo(String hkOnlinePayNo) {
		this.hkOnlinePayNo = hkOnlinePayNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_money
	 * 
	 * @return the value of t_web_bank_huikuan.hk_money
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Double getHkMoney() {
		return hkMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_money
	 * 
	 * @param hkMoney
	 *            the value for t_web_bank_huikuan.hk_money
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkMoney(Double hkMoney) {
		this.hkMoney = hkMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_company_bank
	 * 
	 * @return the value of t_web_bank_huikuan.hk_company_bank
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getHkCompanyBank() {
		return hkCompanyBank;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_company_bank
	 * 
	 * @param hkCompanyBank
	 *            the value for t_web_bank_huikuan.hk_company_bank
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkCompanyBank(String hkCompanyBank) {
		this.hkCompanyBank = hkCompanyBank;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_user_bank
	 * 
	 * @return the value of t_web_bank_huikuan.hk_user_bank
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getHkUserBank() {
		return hkUserBank;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_user_bank
	 * 
	 * @param hkUserBank
	 *            the value for t_web_bank_huikuan.hk_user_bank
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkUserBank(String hkUserBank) {
		this.hkUserBank = hkUserBank;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_user_name
	 * 
	 * @return the value of t_web_bank_huikuan.hk_user_name
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getHkUserName() {
		return hkUserName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_user_name
	 * 
	 * @param hkUserName
	 *            the value for t_web_bank_huikuan.hk_user_name
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkUserName(String hkUserName) {
		this.hkUserName = hkUserName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_ip
	 * 
	 * @return the value of t_web_bank_huikuan.hk_ip
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getHkIp() {
		return hkIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_ip
	 * 
	 * @param hkIp
	 *            the value for t_web_bank_huikuan.hk_ip
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkIp(String hkIp) {
		this.hkIp = hkIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_time
	 * 
	 * @return the value of t_web_bank_huikuan.hk_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Date getHkTime() {
		return hkTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_time
	 * 
	 * @param hkTime
	 *            the value for t_web_bank_huikuan.hk_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkTime(Date hkTime) {
		this.hkTime = hkTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_status
	 * 
	 * @return the value of t_web_bank_huikuan.hk_status
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Integer getHkStatus() {
		return hkStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_status
	 * 
	 * @param hkStatus
	 *            the value for t_web_bank_huikuan.hk_status
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkStatus(Integer hkStatus) {
		this.hkStatus = hkStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_model
	 * 
	 * @return the value of t_web_bank_huikuan.hk_model
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Integer getHkModel() {
		return hkModel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_model
	 * 
	 * @param hkModel
	 *            the value for t_web_bank_huikuan.hk_model
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkModel(Integer hkModel) {
		this.hkModel = hkModel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.modify_time
	 * 
	 * @return the value of t_web_bank_huikuan.modify_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.modify_time
	 * 
	 * @param modifyTime
	 *            the value for t_web_bank_huikuan.modify_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.remark
	 * 
	 * @return the value of t_web_bank_huikuan.remark
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.remark
	 * 
	 * @param remark
	 *            the value for t_web_bank_huikuan.remark
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_check_time
	 * 
	 * @return the value of t_web_bank_huikuan.hk_check_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Date getHkCheckTime() {
		return hkCheckTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_check_time
	 * 
	 * @param hkCheckTime
	 *            the value for t_web_bank_huikuan.hk_check_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkCheckTime(Date hkCheckTime) {
		this.hkCheckTime = hkCheckTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_check_sys_user_name
	 * 
	 * @return the value of t_web_bank_huikuan.hk_check_sys_user_name
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public String getHkCheckSysUserName() {
		return hkCheckSysUserName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_check_sys_user_name
	 * 
	 * @param hkCheckSysUserName
	 *            the value for t_web_bank_huikuan.hk_check_sys_user_name
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkCheckSysUserName(String hkCheckSysUserName) {
		this.hkCheckSysUserName = hkCheckSysUserName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.create_time
	 * 
	 * @return the value of t_web_bank_huikuan.create_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.create_time
	 * 
	 * @param createTime
	 *            the value for t_web_bank_huikuan.create_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_check_status
	 * 
	 * @return the value of t_web_bank_huikuan.hk_check_status
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Integer getHkCheckStatus() {
		return hkCheckStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_check_status
	 * 
	 * @param hkCheckStatus
	 *            the value for t_web_bank_huikuan.hk_check_status
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkCheckStatus(Integer hkCheckStatus) {
		this.hkCheckStatus = hkCheckStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.gmt_4_time
	 * 
	 * @return the value of t_web_bank_huikuan.gmt_4_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Date getGmt4Time() {
		return gmt4Time;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.gmt_4_time
	 * 
	 * @param gmt4Time
	 *            the value for t_web_bank_huikuan.gmt_4_time
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setGmt4Time(Date gmt4Time) {
		this.gmt4Time = gmt4Time;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.total_times
	 * 
	 * @return the value of t_web_bank_huikuan.total_times
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Integer getTotalTimes() {
		return totalTimes;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.total_times
	 * 
	 * @param totalTimes
	 *            the value for t_web_bank_huikuan.total_times
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setTotalTimes(Integer totalTimes) {
		this.totalTimes = totalTimes;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.day_times
	 * 
	 * @return the value of t_web_bank_huikuan.day_times
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Integer getDayTimes() {
		return dayTimes;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.day_times
	 * 
	 * @param dayTimes
	 *            the value for t_web_bank_huikuan.day_times
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setDayTimes(Integer dayTimes) {
		this.dayTimes = dayTimes;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.pay_dama
	 * 
	 * @return the value of t_web_bank_huikuan.pay_dama
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Integer getPayDama() {
		return payDama;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.pay_dama
	 * 
	 * @param payDama
	 *            the value for t_web_bank_huikuan.pay_dama
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setPayDama(Integer payDama) {
		this.payDama = payDama;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.pay_default
	 * 
	 * @return the value of t_web_bank_huikuan.pay_default
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Integer getPayDefault() {
		return payDefault;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.pay_default
	 * 
	 * @param payDefault
	 *            the value for t_web_bank_huikuan.pay_default
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setPayDefault(Integer payDefault) {
		this.payDefault = payDefault;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_web_bank_huikuan.hk_youhui
	 * 
	 * @return the value of t_web_bank_huikuan.hk_youhui
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public Integer getHkYouhui() {
		return hkYouhui;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_web_bank_huikuan.hk_youhui
	 * 
	 * @param hkYouhui
	 *            the value for t_web_bank_huikuan.hk_youhui
	 * @abatorgenerated Sat Nov 22 21:54:12 CST 2014
	 */
	public void setHkYouhui(Integer hkYouhui) {
		this.hkYouhui = hkYouhui;
	}

	public String getPayNo() {
		return payNo;
	}

	public void setPayNo(String payNo) {
		this.payNo = payNo;
	}
	
}