package com.mh.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "T_WEB_THIRD_PAY")
public class TWebThirdPay {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)//自增长
	@Column(name = "ID",nullable = false)
	private Integer id;
	
	@Column(name = "THIRD_NAME")
	private String thirdName;
	
	@Column(name = "THIRD_TYPE")
	private String thirdType;
	
	@Column(name = "THIRD_URL")
	private String thirdUrl;
	
	@Column(name = "THIRD_CODE")
	private String thirdCode;
	
	@Column(name = "THIRD_SECODE")
	private String thirdSecode;
	
	@Column(name = "THIRD_KEY")
	private String thirdKey;
	
	@Column(name = "THIRD_STATUS")
	private Integer thirdStatus;
	
	@Column(name = "THIRD_MIN_EDU")
	private Integer thirdMinEdu;
	
	@Column(name = "THIRD_MAX_EDU")
	private Integer thirdMaxEdu;
	
	@Column(name = "REMARK")
	private String remark;
	
	@Column(name = "CREATE_TIME")
	private Date createTime;
	
	@Column(name = "MODIFY_TIME")
	private Date modifyTime;
	
	@Column(name = "PAY_NO")
	private String payNo;
	
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.id
	 * @param id  the value for t_web_third_pay.id
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_web_third_pay.third_name
	 * @return  the value of t_web_third_pay.third_name
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public String getThirdName() {
		return thirdName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.third_name
	 * @param thirdName  the value for t_web_third_pay.third_name
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setThirdName(String thirdName) {
		this.thirdName = thirdName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_web_third_pay.third_type
	 * @return  the value of t_web_third_pay.third_type
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public String getThirdType() {
		return thirdType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.third_type
	 * @param thirdType  the value for t_web_third_pay.third_type
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setThirdType(String thirdType) {
		this.thirdType = thirdType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_web_third_pay.third_url
	 * @return  the value of t_web_third_pay.third_url
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public String getThirdUrl() {
		return thirdUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.third_url
	 * @param thirdUrl  the value for t_web_third_pay.third_url
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setThirdUrl(String thirdUrl) {
		this.thirdUrl = thirdUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_web_third_pay.third_code
	 * @return  the value of t_web_third_pay.third_code
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public String getThirdCode() {
		return thirdCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.third_code
	 * @param thirdCode  the value for t_web_third_pay.third_code
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setThirdCode(String thirdCode) {
		this.thirdCode = thirdCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_web_third_pay.third_key
	 * @return  the value of t_web_third_pay.third_key
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public String getThirdKey() {
		return thirdKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.third_key
	 * @param thirdKey  the value for t_web_third_pay.third_key
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setThirdKey(String thirdKey) {
		this.thirdKey = thirdKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_web_third_pay.third_status
	 * @return  the value of t_web_third_pay.third_status
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public Integer getThirdStatus() {
		return thirdStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.third_status
	 * @param thirdStatus  the value for t_web_third_pay.third_status
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setThirdStatus(Integer thirdStatus) {
		this.thirdStatus = thirdStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_web_third_pay.third_min_edu
	 * @return  the value of t_web_third_pay.third_min_edu
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public Integer getThirdMinEdu() {
		return thirdMinEdu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.third_min_edu
	 * @param thirdMinEdu  the value for t_web_third_pay.third_min_edu
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setThirdMinEdu(Integer thirdMinEdu) {
		this.thirdMinEdu = thirdMinEdu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_web_third_pay.third_max_edu
	 * @return  the value of t_web_third_pay.third_max_edu
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public Integer getThirdMaxEdu() {
		return thirdMaxEdu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_web_third_pay.third_max_edu
	 * @param thirdMaxEdu  the value for t_web_third_pay.third_max_edu
	 * @abatorgenerated  Fri Sep 26 20:25:42 CST 2014
	 */
	public void setThirdMaxEdu(Integer thirdMaxEdu) {
		this.thirdMaxEdu = thirdMaxEdu;
	}

	
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getThirdSecode() {
		return thirdSecode;
	}

	public void setThirdSecode(String thirdSecode) {
		this.thirdSecode = thirdSecode;
	}

	public String getPayNo() {
		return payNo;
	}

	public void setPayNo(String payNo) {
		this.payNo = payNo;
	}
	
	
}