/*
Navicat MySQL Data Transfer

Source Server         : [阿里云]web-master
Source Server Version : 50623
Source Host           : 127.0.0.1:3306
Source Database       : 399bf.com

Target Server Type    : MYSQL
Target Server Version : 50623
File Encoding         : 65001

Date: 2017-05-15 15:00:02
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for v9_category
-- ----------------------------
DROP TABLE IF EXISTS `v9_category`;
CREATE TABLE `v9_category` (
  `catid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `module` varchar(15) NOT NULL,
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `modelid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `parentid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `arrparentid` varchar(255) NOT NULL,
  `child` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `arrchildid` mediumtext NOT NULL,
  `catname` varchar(30) NOT NULL,
  `style` varchar(5) NOT NULL,
  `image` varchar(100) NOT NULL,
  `description` mediumtext NOT NULL,
  `parentdir` varchar(100) NOT NULL,
  `catdir` varchar(30) NOT NULL,
  `url` varchar(100) NOT NULL,
  `items` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `setting` mediumtext NOT NULL,
  `listorder` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ismenu` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `sethtml` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `letter` varchar(30) NOT NULL,
  `usable_type` varchar(255) NOT NULL,
  PRIMARY KEY (`catid`),
  KEY `module` (`module`,`parentid`,`listorder`,`catid`) USING BTREE,
  KEY `siteid` (`siteid`,`type`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=39 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of v9_category
-- ----------------------------
INSERT INTO `v9_category` VALUES ('1', '1', 'content', '0', '1', '0', '0', '1', '1,18,19,20,21,22', '足彩分析', '', '', '', '', 'zcfx', 'http://www.399cm.com/zcfx/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u8db3\\u5f69\\u5206\\u6790\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '1', '1', '0', 'zucaifenxi', '');
INSERT INTO `v9_category` VALUES ('2', '1', 'content', '0', '1', '0', '0', '1', '2,24,25', '足彩预测', '', '', '', '', 'zcyc', 'http://www.399cm.com/zcyc/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u8db3\\u5f69\\u9884\\u6d4b\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '2', '1', '0', 'zucaiyuce', '');
INSERT INTO `v9_category` VALUES ('3', '1', 'content', '0', '1', '0', '0', '1', '3,27,31', '足彩推荐', '', '', '', '', 'zctj', 'http://www.399cm.com/zctj/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u8db3\\u5f69\\u63a8\\u8350\\uff0c\\u7ade\\u5f69\\u8db3\\u7403\\u63a8\\u8350\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '3', '1', '0', 'zucaituijian', '');
INSERT INTO `v9_category` VALUES ('4', '1', 'content', '0', '1', '0', '0', '0', '4', '竞彩篮球预测', '', '', '', '', 'jclqyc', 'http://www.399cm.com/jclqyc/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '4', '1', '0', 'jingcailanqiuyuce', '');
INSERT INTO `v9_category` VALUES ('5', '1', 'content', '0', '1', '0', '0', '0', '5', '竞彩篮球分析', '', '', '', '', 'jclqfx', 'http://www.399cm.com/jclqfx/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '5', '1', '0', 'jingcailanqiufenxi', '');
INSERT INTO `v9_category` VALUES ('6', '1', 'content', '0', '1', '0', '0', '1', '6,28,29,30,37,38', '竞彩体育资讯', '', '', '', '', 'tyzx', 'http://www.399cm.com/tyzx/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '6', '1', '0', 'jingcaitiyuzixun', '');
INSERT INTO `v9_category` VALUES ('7', '1', 'content', '0', '3', '0', '0', '1', '7,9,10,11,12,13,14,15,16,32,33,34,35,36', '体坛图库', '', '', '', '', 'tuku', 'http://www.399cm.com/tuku/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '7', '1', '0', 'titantuku', '');
INSERT INTO `v9_category` VALUES ('31', '1', 'content', '0', '1', '3', '0,3', '0', '31', '足彩单场分析', '', '', '', 'zctj/', 'zcdcfx', 'http://www.399cm.com/zcdcfx/', '107', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u8db3\\u5f69\\u5355\\u573a\\u5206\\u6790\\uff0c\\u4eca\\u65e5\\u8db3\\u5f69\\u5206\\u6790\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '31', '1', '0', 'zucaidanchangfenxi', '');
INSERT INTO `v9_category` VALUES ('9', '1', 'content', '0', '3', '7', '0,7', '1', '9,10,11,12', '足球宝贝', '', '', '', 'tuku/', 'zqbaobei', 'http://www.399cm.com/zqbaobei/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\\u8db3\\u7403\\u5b9d\\u8d1d\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '9', '1', '0', 'zuqiubaobei', '');
INSERT INTO `v9_category` VALUES ('10', '1', 'content', '0', '3', '9', '0,7,9', '0', '10', '足球宝贝图片', '', '', '', 'tuku/zqbaobei/', 'zqbbpic', 'http://www.399cm.com/zqbbpic/', '69', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\\u8db3\\u7403\\u5b9d\\u8d1d\\u56fe\\u7247\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '10', '1', '0', 'zuqiubaobeitupian', '');
INSERT INTO `v9_category` VALUES ('11', '1', 'content', '0', '3', '9', '0,7,9', '0', '11', '足球宝贝壁纸', '', '', '', 'tuku/zqbaobei/', 'zqbbbz', 'http://www.399cm.com/zqbbbz/', '15', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\\u8db3\\u7403\\u5b9d\\u8d1d\\u58c1\\u7eb8\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '11', '1', '0', 'zuqiubaobeibizhi', '');
INSERT INTO `v9_category` VALUES ('12', '1', 'content', '0', '3', '9', '0,7,9', '0', '12', '英超宝贝', '', '', '', 'tuku/zqbaobei/', 'ycbaobei', 'http://www.399cm.com/ycbaobei/', '27', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '12', '1', '0', 'yingchaobaobei', '');
INSERT INTO `v9_category` VALUES ('13', '1', 'content', '0', '3', '7', '0,7', '1', '13,14,15,16', '篮球宝贝', '', '', '', 'tuku/', 'lqbaobei', 'http://www.399cm.com/lqbaobei/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '13', '1', '0', 'lanqiubaobei', '');
INSERT INTO `v9_category` VALUES ('14', '1', 'content', '0', '3', '13', '0,7,13', '0', '14', 'nba篮球宝贝', '', '', '', 'tuku/lqbaobei/', 'nbabaobei', 'http://www.399cm.com/nbabaobei/', '14', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"nba\\u7bee\\u7403\\u5b9d\\u8d1d\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '14', '1', '0', 'nbalanqiubaobei', '');
INSERT INTO `v9_category` VALUES ('15', '1', 'content', '0', '3', '13', '0,7,13', '0', '15', 'cba篮球宝贝', '', '', '', 'tuku/lqbaobei/', 'cbabaobei', 'http://www.399cm.com/cbabaobei/', '28', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"cba\\u7bee\\u7403\\u5b9d\\u8d1d\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '15', '1', '0', 'cbalanqiubaobei', '');
INSERT INTO `v9_category` VALUES ('16', '1', 'content', '0', '3', '13', '0,7,13', '0', '16', '篮球宝贝壁纸', '', '', '', 'tuku/lqbaobei/', 'lqbbbz', 'http://www.399cm.com/lqbbbz/', '18', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\\u7bee\\u7403\\u5b9d\\u8d1d\\u58c1\\u7eb8\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '16', '1', '0', 'lanqiubaobeibizhi', '');
INSERT INTO `v9_category` VALUES ('18', '1', 'content', '0', '1', '1', '0,1', '0', '18', '竞彩足球分析', '', '', '', 'zcfx/', 'jczqfx', 'http://www.399cm.com/jczqfx/', '8', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u7ade\\u5f69\\u8db3\\u7403\\u5206\\u6790\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '18', '1', '0', 'jingcaizuqiufenxi', '');
INSERT INTO `v9_category` VALUES ('19', '1', 'content', '0', '1', '1', '0,1', '0', '19', '亚盘分析法', '', '', '', 'zcfx/', 'ypfxf', 'http://www.399cm.com/ypfxf/', '14', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u4e9a\\u76d8\\u5206\\u6790\\u6cd5\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '19', '1', '0', 'yapanfenxifa', '');
INSERT INTO `v9_category` VALUES ('20', '1', 'content', '0', '1', '1', '0,1', '0', '20', '欧赔分析技巧', '', '', '', 'zcfx/', 'opfxjq', 'http://www.399cm.com/opfxjq/', '33', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u6b27\\u8d54\\u5206\\u6790\\u6280\\u5de7\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '20', '1', '0', 'oupeifenxijiqiao', '');
INSERT INTO `v9_category` VALUES ('21', '1', 'content', '0', '1', '1', '0,1', '0', '21', '欧赔和亚盘', '', '', '', 'zcfx/', 'ephyp', 'http://www.399cm.com/ephyp/', '15', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u6b27\\u8d54\\u548c\\u4e9a\\u76d8\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '21', '1', '0', 'oupeiheyapan', '');
INSERT INTO `v9_category` VALUES ('22', '1', 'content', '0', '1', '1', '0,1', '0', '22', '竞彩足球怎么玩', '', '', '', 'zcfx/', 'jczqzmw', 'http://www.399cm.com/jczqzmw/', '3', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u7ade\\u5f69\\u8db3\\u7403\\u600e\\u4e48\\u73a9\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '22', '1', '0', 'jingcaizuqiuzenmewan', '');
INSERT INTO `v9_category` VALUES ('24', '1', 'content', '0', '1', '2', '0,2', '0', '24', '竞彩足球预测', '', '', '', 'zcyc/', 'jczqyc', 'http://www.399cm.com/jczqyc/', '87', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u7ade\\u5f69\\u8db3\\u7403\\u9884\\u6d4b\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '24', '1', '0', 'jingcaizuqiuyuce', '');
INSERT INTO `v9_category` VALUES ('25', '1', 'content', '0', '1', '2', '0,2', '0', '25', '胜负彩14场专家预测', '', '', '', 'zcyc/', 'sfcyc', 'http://www.399cm.com/sfcyc/', '7', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u80dc\\u8d1f\\u5f6914\\u573a\\u4e13\\u5bb6\\u9884\\u6d4b\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '25', '1', '0', 'shengfucai14changzhuanjiayuce', '');
INSERT INTO `v9_category` VALUES ('27', '1', 'content', '0', '1', '3', '0,3', '0', '27', '今日强胆推荐', '', '', '', 'zctj/', 'jrqdtj', 'http://www.399cm.com/jrqdtj/', '37', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u4eca\\u65e5\\u5f3a\\u80c6\\u63a8\\u8350\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '27', '1', '0', 'jinriqiangdantuijian', '');
INSERT INTO `v9_category` VALUES ('28', '1', 'content', '0', '1', '6', '0,6', '0', '28', '五大联赛', '', '', '', 'tyzx/', 'wdls', 'http://www.399cm.com/wdls/', '42', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u4e94\\u5927\\u8054\\u8d5b\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '28', '1', '0', 'wudaliansai', '');
INSERT INTO `v9_category` VALUES ('29', '1', 'content', '0', '1', '6', '0,6', '0', '29', '中国足坛', '', '', '', 'tyzx/', 'cnzt', 'http://www.399cm.com/cnzt/', '56', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u4e2d\\u56fd\\u8db3\\u575b\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '29', '1', '0', 'zhongguozutan', '');
INSERT INTO `v9_category` VALUES ('30', '1', 'content', '0', '1', '6', '0,6', '0', '30', '世界足坛', '', '', '', 'tyzx/', 'sjzt', 'http://www.399cm.com/sjzt/', '24', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\\u4e16\\u754c\\u8db3\\u575b\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '30', '1', '0', 'shijiezutan', '');
INSERT INTO `v9_category` VALUES ('8', '1', 'content', '0', '11', '0', '0', '0', '8', '体坛视频', '', '', '', '', 'video', 'http://www.399cm.com/video/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_video\",\"list_template\":\"list_video\",\"show_template\":\"show_video\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '8', '1', '0', 'titanshipin', '');
INSERT INTO `v9_category` VALUES ('32', '1', 'content', '0', '3', '7', '0,7', '1', '32,33,34,35,36', '体坛美图', '', '', '', 'tuku/', 'ttmt', 'http://www.399cm.com/ttmt/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '32', '1', '0', 'titanmeitu', '');
INSERT INTO `v9_category` VALUES ('33', '1', 'content', '0', '3', '32', '0,7,32', '0', '33', '养眼美女', '', '', '', 'tuku/ttmt/', 'yymv', 'http://www.399cm.com/yymv/', '33', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '33', '1', '0', 'yangyanmeinv', '');
INSERT INTO `v9_category` VALUES ('34', '1', 'content', '0', '3', '32', '0,7,32', '0', '34', '精彩赛况', '', '', '', 'tuku/ttmt/', 'jcsk', 'http://www.399cm.com/jcsk/', '10', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '34', '1', '0', 'jingcaisaikuang', '');
INSERT INTO `v9_category` VALUES ('35', '1', 'content', '0', '3', '32', '0,7,32', '0', '35', '搞笑趣图', '', '', '', 'tuku/ttmt/', 'gxqt', 'http://www.399cm.com/gxqt/', '7', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '35', '1', '0', 'gaoxiaoqutu', '');
INSERT INTO `v9_category` VALUES ('36', '1', 'content', '0', '3', '32', '0,7,32', '0', '36', '巨星风采', '', '', '', 'tuku/ttmt/', 'jxfc', 'http://www.399cm.com/jxfc/', '21', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_picture\",\"list_template\":\"list_picture\",\"show_template\":\"show_picture\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '36', '1', '0', 'juxingfengcai', '');
INSERT INTO `v9_category` VALUES ('37', '1', 'content', '0', '1', '6', '0,6', '0', '37', '精彩赛况', '', '', '精彩赛况', 'tyzx/', 'jjsk', 'http://www.399cm.com/jjsk/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '37', '1', '0', 'jingcaisaikuang', '');
INSERT INTO `v9_category` VALUES ('38', '1', 'content', '0', '1', '6', '0,6', '0', '38', '花边趣闻', '', '', '', 'tyzx/', 'hbqw', 'http://www.399cm.com/hbqw/', '0', '0', '{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}', '38', '1', '0', 'huabianquwen', '');
