package com.mh.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "T_LINK_WEB_USER_THIRD_PAY")
public class TLinkWebUserThirdPay {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)//自增长
	@Column(name = "ID",nullable = false)
    private Integer id;

	@Column(name = "USER_TYPE_ID")
    private Integer userTypeId;

	@Column(name = "USER_THIRD_PAY_ID")
    private Integer userThirdPayId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_link_web_user_third_pay.id
     *
     * @return the value of t_link_web_user_third_pay.id
     *
     * @abatorgenerated Sat Sep 27 00:15:11 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_link_web_user_third_pay.id
     *
     * @param id the value for t_link_web_user_third_pay.id
     *
     * @abatorgenerated Sat Sep 27 00:15:11 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_link_web_user_third_pay.user_type_id
     *
     * @return the value of t_link_web_user_third_pay.user_type_id
     *
     * @abatorgenerated Sat Sep 27 00:15:11 CST 2014
     */
    public Integer getUserTypeId() {
        return userTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_link_web_user_third_pay.user_type_id
     *
     * @param userTypeId the value for t_link_web_user_third_pay.user_type_id
     *
     * @abatorgenerated Sat Sep 27 00:15:11 CST 2014
     */
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_link_web_user_third_pay.user_third_pay_id
     *
     * @return the value of t_link_web_user_third_pay.user_third_pay_id
     *
     * @abatorgenerated Sat Sep 27 00:15:11 CST 2014
     */
    public Integer getUserThirdPayId() {
        return userThirdPayId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_link_web_user_third_pay.user_third_pay_id
     *
     * @param userThirdPayId the value for t_link_web_user_third_pay.user_third_pay_id
     *
     * @abatorgenerated Sat Sep 27 00:15:11 CST 2014
     */
    public void setUserThirdPayId(Integer userThirdPayId) {
        this.userThirdPayId = userThirdPayId;
    }
}