<%@ page language="java" import="java.util.*,com.mh.commons.constants.*"
  contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ page import="com.mh.commons.utils.ServletUtils"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="mh" uri="http://www.mh.com/framework/tags" %>
 
    <link rel="stylesheet" href="${resourceRoot }/production/css/vendor.min.css" />
    <link rel="stylesheet" href="${resourceRoot }/production/css/main.min.css" />

	<!--[if IE]>
	<link rel="stylesheet" href="${resourceRoot }/production/css/ie.css" />
	<![endif]-->
  
	<script type="text/javascript" src="${resourceRoot }/production/vendor.min.js"></script>
    <script type="text/javascript" src="${resourceRoot }/production/main.min.js"></script>

